---
php_supported_os_family:
  debian: debian.yml

php_ubuntu_packages:
  - php8.1
  - php8.1-dev
  - php8.1-bcmath
  - php8.1-intl
  - php8.1-soap
  - php8.1-zip
  - php8.1-curl
  - php8.1-mbstring
  - php8.1-mysql
  - php8.1-gd
  - php8.1-xml
  - php8.1-fpm
