---
# handlers file for initapps
- name: Reload nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart php8.1-fpm
  become: true
  ansible.builtin.service:
    name: php8.1-fpm
    state: restarted
